### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by guanzhangrtk** [guanzhangrtk/rotkbot#1]
App crashed on ZEIT, AFAIK nobody ran any commands at that time so not exactly sure what happened, I need to double check that the bot is available only in that one Discord channel. Here's the log:

```
11/07 06:21 PM (3h)
[11/8/2018, 02:21:09] Updating file ./data/participants.json... done
11/07 06:58 PM (2h)
/home/nowuser/src/rotk.js:192
11/07 06:58 PM (2h)
  let sender = bot.users[userID].username;
11/07 06:58 PM (2h)
                                 ^
11/07 06:58 PM (2h)
11/07 06:58 PM (2h)
TypeError: Cannot read property 'username' of undefined
11/07 06:58 PM (2h)
    at DiscordClient.<anonymous> (/home/nowuser/src/rotk.js:192:34)
11/07 06:58 PM (2h)
    at emitMany (events.js:147:13)
11/07 06:58 PM (2h)
    at DiscordClient.emit (events.js:224:7)
11/07 06:58 PM (2h)
    at DiscordClient.handleWSMessage (/home/nowuser/src/node_modules/discord.io/lib/index.js:1848:11)
11/07 06:58 PM (2h)
    at emitTwo (events.js:126:13)
11/07 06:58 PM (2h)
    at WebSocket.emit (events.js:214:7)
11/07 06:58 PM (2h)
    at Receiver.ontext (/home/nowuser/src/node_modules/ws/lib/WebSocket.js:841:10)
11/07 06:58 PM (2h)
    at /home/nowuser/src/node_modules/ws/lib/Receiver.js:536:18
11/07 06:58 PM (2h)
    at Receiver.applyExtensions (/home/nowuser/src/node_modules/ws/lib/Receiver.js:371:5)
11/07 06:58 PM (2h)
    at /home/nowuser/src/node_modules/ws/lib/Receiver.js:508:14
11/07 06:58 PM (2h)
npm ERR! code ELIFECYCLE
11/07 06:58 PM (2h)
npm ERR! errno 1
11/07 06:58 PM (2h)
npm ERR! rotk-bot@1.0.0 start: `node rotk.js`
11/07 06:58 PM (2h)
npm ERR! Exit status 1
11/07 06:58 PM (2h)
npm ERR! 
11/07 06:58 PM (2h)
npm ERR! Failed at the rotk-bot@1.0.0 start script.
11/07 06:58 PM (2h)
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11/07 06:58 PM (2h)
11/07 06:58 PM (2h)
npm ERR! A complete log of this run can be found in:
11/07 06:58 PM (2h)
npm ERR!     /home/nowuser/.npm/_logs/2018-11-08T02_58_54_334Z-debug.log
11/07 06:58 PM (2h)
npm start
11/07 06:58 PM (2h)
11/07 06:58 PM (2h)
> rotk-bot@1.0.0 start /home/nowuser/src
11/07 06:58 PM (2h)
> node rotk.js
```

**Comment by guanzhangrtk** [comment]
Turns out it was because the bot was reading messages sent by Zapier, and since Webhooks don't have UserIDs, it crashed. Should be fixed in ea4f14cae88b67ce10a64dc73b5a5fe29fa33468.
